### ISSUE TITLE
EmbeddedInput instead of ReferenceInput to use embedded data coming from the server

### ISSUE THREAD

**Issue by zifnab87** [MhdSyrwan/aor-embedded-array#5]
I think that along the same lines that EmbeddedArrayInput works there is need for EmbeddedInput that works for one element - something that would solve my issues here: https://stackoverflow.com/questions/46592926/how-to-leverage-embedded-resources-in-referencearrayinput-and-referencearrayfiel
https://stackoverflow.com/questions/46592587/how-to-correctly-render-referenced-entities-in-list-when-i-have-objects-instead

Unless it works for one or many inputs at the same time - I will try it

Thanks!

**Comment by MhdSyrwan** [comment]
You can use `EmbeddedArrayInput` to solve your problem. but you need to write a custom selectbox input to be put inside it.
That select box should return a value like `{id: "1", name: "name 1" }` and display only the `name`.

I'm closing this since it's a general AOR question and also application related. it's too far from the purpose of `aor-embedded-array`
